### ISSUE TITLE
Deprecated selector in `clojure-plus/styles/clojure-plus.less`

### ISSUE THREAD

**Issue by barbagrigia** [mauricioszabo/clojure-plus#21]
In `clojure-plus/styles/clojure-plus.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .selection .region,
atom-text-editor::shadow :host .selection .region` => `atom-text-editor.editor .selection .region,
atom-text-editor.editor :host .selection .region`

* `atom-text-editor::shadow .clojure-watch-expr .region` => `atom-text-editor.editor .clojure-watch-expr .region`

* `atom-text-editor::shadow .clojure-watch-expr.watch .region` => `atom-text-editor.editor .clojure-watch-expr.watch .region`

* `atom-text-editor::shadow .clojure-sexp .region` => `atom-text-editor.editor .clojure-sexp .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by mauricioszabo** [comment]
Closed by #22
